#!/usr/bin/env python
# -*-coding:utf-8 -*-

from optparse import OptionParser

import numpy as np
import pandas as pd
from math import ceil

def parse():
    usage = 'usage: %prog <tab> <num_range>'
    parser = OptionParser(usage)
    parser.add_option('-t', '--table', dest = 'data', help='table file')
    parser.add_option('-n', '--num_range', dest = 'range', help='repeat num range, start:end:stride', default="1:3:2", type=str)
    parser.add_option('-s', '--sep', dest = 'sep', help='table file sep, default:" "', default=' ', type=str)
    (options, args) = parser.parse_args()
    return options.data, options.range, options.sep

def main():
    table_dir, num_range, sep = parse()
    table = pd.read_csv(table_dir, sep=sep, index_col=None, header=None)
    if num_range.count(":") == 2:
        start, end, stride = list(map(int, num_range.split(":")))
    else:
        raise ValueError("--num_range should be at start:end:stride not {num_range}")
    range_array = np.arange(start, end, stride)
    range_num_series = pd.DataFrame(np.tile(range_array, ceil(table.shape[0]/len(range_array)))[:table.shape[0]], dtype=object)
    table = pd.concat([table, range_num_series], axis=1)
    
    table.to_csv(table_dir, sep=sep, index=None, header=None)

if __name__ == "__main__":
    main()
