#!/usr/bin/env python
# -*-coding:utf-8 -*-

import argparse
import os
import os.path as osp
import shutil
import sys


def mkdirs(path):
    try:
        os.makedirs(path)
    except:
        pass


def getParser():
    parser = argparse.ArgumentParser(
        description=f"-i alphafold2 output dir -o pdb_save_path, rank_0 will be saved "
    )

    parser.add_argument(
        "-i",
        "--input",
        dest="target_dir",
        type=str,
        required=True,
        help=" alphafold2 output dir",
    )  #  this will

    parser.add_argument("-o", "--output", dest="output_dir", type=str, required=True)

    return parser


if __name__ == "__main__":
    parser = getParser()
    args = parser.parse_args()
    target_dir = args.target_dir
    pdb_name = target_dir.split(os.sep)[-1]

    output_dir = args.output_dir

    mkdirs(output_dir)

    osp.split(os.sep)

    try:
        _from = osp.join(target_dir, "ranked_0.pdb")
        _to = osp.join(output_dir, pdb_name + ".pdb")
        print()
        shutil.copy(_from, _to)
    except IOError as e:
        print("Unable to copy file. %s" % e)
    except:
        print("Unexpected error:", sys.exc_info())

    # for i in range(5):
    #     try:
    #         _from = osp.join(target_dir, f"ranked_{i}.pdb")
    #         _to = osp.join(output_dir, pdb_name + f"_{i}.pdb")
    #         shutil.copy(_from, _to)
    #     except IOError as e:
    #         print("Unable to copy file. %s" % e)
    #     except:
    #         print("Unexpected error:", sys.exc_info())
